# Generated by Django 3.0.3 on 2020-03-02 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200229_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='title',
        ),
    ]
