# Generated by Django 3.0.3 on 2020-03-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is test description sdne inowncwncw inonisc'),
            preserve_default=False,
        ),
    ]
