# Generated by Django 2.2.10 on 2020-03-05 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20200303_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='oredered',
            new_name='ordered',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Ordered_date',
            new_name='ordered_date',
        ),
    ]
